# Generated by Django 3.2.25 on 2025-07-26 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SN_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('sn', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('current_opid', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('current_routing_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('prev_station', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('current_station', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('next_station', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('uuid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=1, null=True)),
                ('work_order', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkOrder_sn', to='api.workorder')),
            ],
            options={
                'unique_together': {('work_order', 'sn')},
            },
        ),
    ]
