# Generated by Django 3.2.25 on 2025-07-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sn_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('customer_project', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('plant', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('formatmask', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('formatmask_pack', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('carton_min_weigth', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('carton_max_weigth', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('giftbox_min_weigth', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('giftbox_max_weigth', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('create_date', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qty_per_box', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('thr_prepacking', models.IntegerField(blank=True, default=1)),
                ('mix_workorder', models.BooleanField(default=False)),
                ('require_register_sn', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('qty', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('boxbuild', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('need_validate_sn', models.BooleanField(default=False)),
                ('validate_sn_type', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('project_master', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_master', to='api.project_master')),
            ],
        ),
    ]
